"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard_category_txns from './dashboard-category-txns.bones.json'
import _transactions_list from './transactions-list.bones.json'
import _lists_sheet_results from './lists-sheet-results.bones.json'
import _splits_list from './splits-list.bones.json'

registerBones({
  "dashboard-category-txns": _dashboard_category_txns,
  "transactions-list": _transactions_list,
  "lists-sheet-results": _lists_sheet_results,
  "splits-list": _splits_list,
})
